version: 2
jobs:
  build:
    docker:
      - image: blang/latex:ctanfull
    steps:
      - checkout
      - run: mkdir .fonts
      - run: git clone git://github.com/google/fonts.git .fonts/google-fonts
      - run: fc-cache -f
      - run: make
